In [1]:
import pandas as pd
import numpy as np

headers = ['timestamp', 'pipeline', 'classifier', 'error_generator',
           'column', 'data_type', 'result', 'failed_step']
results = pd.read_csv('resources/results/log.csv', sep=';', names=headers)
results = results.fillna('pass')

In [2]:
np.sum(results['failed_step'] == 'pass') / results.shape[0]

0.32507666902571364

In [3]:
# all typos fail
np.sum((results['error_generator'] == 'typos') & (results['failed_step'] == 'pass'))

0

In [4]:
# numeric anomalies fail partially only with HeartPipeline
mask = (results['error_generator'] == 'numeric anomalies') & (results['failed_step'] != 'pass')
list(np.unique(results[mask]['pipeline']))

['heart']

In [9]:
# numeric anomalies fail with HeartPipeline one hot encoders
mask = ((results['error_generator'] == 'numeric anomalies')
        & (results['pipeline'] == 'heart'))
results[mask]['result'].unique()

array(['0.7963', '0.8333', '0.7778',
       'Anomalies: Found unknown categories [5] in column 0 during fit',
       '0.8148',
       'Anomalies: Found unknown categories [4] in column 0 during fit',
       'Anomalies: Found unknown categories [-1] in column 0 during fit',
       'Anomalies: Found unknown categories [6] in column 0 during fit',
       'Anomalies: Found unknown categories [0] in column 0 during fit',
       'Anomalies: Found unknown categories [-2] in column 0 during fit',
       'Anomalies: Found unknown categories [11] in column 0 during fit',
       '0.6667', '0.6852', '0.6296', '0.7037',
       'Anomalies: Found unknown categories [12] in column 0 during fit',
       '0.8519', '0.5741', '0.5926', '0.7593',
       'Anomalies: Found unknown categories [10] in column 0 during fit'],
      dtype=object)

In [6]:
results[results['error_generator'] == 'implicit misvals'].groupby(['data_type', 'failed_step'])['timestamp'].count()

data_type  failed_step
num cont   column transformers     77
           one hot encoders       275
           pass                    22
           transformers           150
num disc   column transformers     77
           one hot encoders       275
           pass                    22
           transformers           150
string     column transformers    143
           one hot encoders        22
           transformers           200
Name: timestamp, dtype: int64

In [7]:
# implicit misvals fail everywhere except WineQuality- and WineQualityMissing- Pipeline
#

In [8]:
results[results['error_generator'] == 'explicit misvals'].groupby(['pipeline', 'data_type', 'failed_step']).count()

                                             timestamp  classifier  \
pipeline      data_type failed_step
abalone       num cont  pass                        14          14
                        scaler                     140         140
              num disc  pass                        14          14
                        scaler                     140         140
              string    one hot encoders            22          22
adult         num cont  pass                        84          84
              num disc  pass                        84          84
              string    transformers               112         112
adult-missing num cont  pass                        66          66
              num disc  pass                        66          66
              string    transformers                88          88
credit-g      num cont  pass                         7           7
                        scaler                      70          70
              num disc  pass                         7           7
                        scaler                      70          70
              string    column transformers        143         143
heart         num cont  one hot encoders            55          55
                        pass                         6           6
                        scaler                      60          60
              num disc  one hot encoders            55          55
                        pass                         6           6
                        scaler                      60          60
wine-quality  num cont  pass                         1           1
                        scaler                      10          10
              num disc  pass                         1           1
                        scaler                      10          10
wq-missing    num cont  pass                        11          11
              num disc  pass                        11          11

                                             error_generator  column  result
pipeline      data_type failed_step
abalone       num cont  pass                              14      14      14
                        scaler                           140     140     140
              num disc  pass                              14      14      14
                        scaler                           140     140     140
              string    one hot encoders                  22      22      22
adult         num cont  pass                              84      84      84
              num disc  pass                              84      84      84
              string    transformers                     112     112     112
adult-missing num cont  pass                              66      66      66
              num disc  pass                              66      66      66
              string    transformers                      88      88      88
credit-g      num cont  pass                               7       7       7
                        scaler                            70      70      70
              num disc  pass                               7       7       7
                        scaler                            70      70      70
              string    column transformers              143     143     143
heart         num cont  one hot encoders                  55      55      55
                        pass                               6       6       6
                        scaler                            60      60      60
              num disc  one hot encoders                  55      55      55
                        pass                               6       6       6
                        scaler                            60      60      60
wine-quality  num cont  pass                               1       1       1
                        scaler                            10      10      10
              num disc  pass                               1       1       1
                        scaler                            10      10      10
wq-missing    num cont  pass                              11      11      11
              num disc  pass                              11      11      11